import java.util.ArrayList;


/**
 * <h1>Truck</h1> Represents a Truck
 */
public class Truck extends Vehicle implements Profitable {

    private final double GAS_RATE = 1.66;

    private String licensePlate;
    private double maxWeight;
    private double currentWeight;
    private int zipDest;
    private ArrayList<Package> packages;


    /**
     * Default Constructor
     */
    //============================================================================
    public Truck() {
        this.licensePlate = "";
        this.maxWeight = 0.0;
        this.currentWeight = 0.0;
        this.zipDest = 0;
        this.packages = new ArrayList<>();

    }

    //============================================================================

    /**
     * Constructor
     *
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    public Truck(String licensePlate, double maxWeight) {
        super();
        this.maxWeight = maxWeight;
        this.licensePlate = licensePlate;
    }

    //============================================================================

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */
    public void fill(ArrayList<Package> warehousePackages) {
        

    }
    /**
     * Returns the profits generated by the packages currently in the Vehicle.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 1.66)
     * </p>
     */
    @Override
    public double getProfit() {

        double range = 0; // Put the range here
        double difference = range * GAS_RATE;
        double sum = 0.0;

        for (Package p: packages) {
            sum += p.getPrice();
        }

        return sum - difference;

    }

    /**
     * Generates a String of the truck report. Truck report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in truck</li>
     * </ul>
     *
     * @return Truck Report
     */
    @Override
    public String report() {
        Truck truck = new Truck();

        String output = "==========Truck Report==========\n";
        output += "License Plate No.: " + truck.getLicensePlate() + "\n";
        output += "Destination: " + truck.getZipDest() + "\n";
        output += "Weight Load: " + truck.getCurrentWeight() + "/" + truck.getMaxWeight() + "\n";
        output += "Net Profit: (" + getProfit() + ")" + "\n";
        output += "==============================" + "\n";
        return output;

    }


}