/**
 * <h1>Truck</h1> Represents a Truck
 *
 * @author Junseok
 * @author JJaved
 * @version 12-03-18
 */
public class Truck extends Vehicle implements Profitable {

    private final double gasRate = 1.66;
    /**
     * Default Constructor
     */
    //============================================================================
    public Truck() {
        super();
    }

    //============================================================================

    /**
     * Constructor
     *
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    public Truck(String licensePlate, double maxWeight) {
        super(licensePlate, maxWeight);
    }

    //============================================================================

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */

    /**
     * Returns the profits generated by the packages currently in the Vehicle.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 1.66)
     * </p>
     */
    public double getProfit() {
        double difference = super.maxRange * gasRate;
        double sum = super.getProfit();
        return sum - difference;

    }
    /**
     * Generates a String of the truck report. Truck report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in truck</li>
     * </ul>
     *
     * @return Truck Report
     */
    @Override
    public String report() {
        String output = "==========Truck Report==========\n";
        output += String.format("License Plate No.: %s\n" +
                        "Destination: %d\n" +
                        "Weight Load: %.2f/%.2f\n", getLicensePlate(), getZipDest(),
                getCurrentWeight(), getMaxWeight());
        if (getProfit() < 0) {
            output += String.format("Net Profit: ($%.2f)\n", -1 * getProfit());
        } else {
            output += String.format("Net Profit: $%.2f\n", getProfit());
        }
        for (Package packa : getPackages()) {
            output += "=====Shipping Labels=====\n";

            output += packa.shippingLabel();

        }
        output += "\n==============================" + "\n";
        return output;


    }


}